# Use the official Node.js image as a base image
FROM node:20-alpine3.20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code into the container
COPY . .

# Add entrypoint script
COPY entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# Expose the port the app runs on
EXPOSE 3333

# Set the entrypoint script
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

# Start the application
CMD ["npm", "run", "start:dev"]
