name: CI/CD Pipeline for Azure Busify Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/busify:latest ./backend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/busify:latest

      - name: Azure Login with Managed Identity
        run: |
          az login --identity --username ${{ secrets.AZURE_UAMI_CLIENT_ID }}


      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name busify \
            --resource-group busify-resource \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/busify:latest
