name: CI/CD Pipeline for Azure Busify Container App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/busify:latest5 ./backend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/busify:latest5

      - name: Azure Login with User-Assigned Managed Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name busify \
            --resource-group busify-resource \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/busify:latest5